import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'regenerator-runtime/runtime';
import Container from '@/layouts/Container';
import Sidebar from '@/layouts/Sidebar';
import Main from '@/layouts/Main';
import Aside from '@/components/Aside';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <Sidebar>
            <Aside />
          </Sidebar>
          <Main>{children}</Main>
        </Container>
      </body>
    </html>
  );
}
